services:
  back:
    container_name: back
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - GOTRUE_DB_MIGRATIONS_PATH=/app/migrations
    volumes:
      - ./auth:/auth:Z
      - .env:/.env:Z
      - ./migrations:/migrations:Z
    command: back
    restart: unless-stopped
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: back_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      # sets the schema name, this should match the `NAMESPACE` env var set in your .env file
      - DB_NAMESPACE=auth
    restart: unless-stopped
volumes:
  postgres_data:
