#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER admin LOGIN CREATEROLE CREATEDB REPLICATION BYPASSRLS;

    -- Supabase super admin
    CREATE USER back_admin NOINHERIT CREATEROLE LOGIN NOREPLICATION PASSWORD '$POSTGRES_PASSWORD';
    CREATE SCHEMA IF NOT EXISTS $DB_NAMESPACE AUTHORIZATION back_admin;
    GRANT CREATE ON DATABASE postgres TO back_admin;
    ALTER USER back_admin SET search_path = '$DB_NAMESPACE';
EOSQL
