CREATE USER admin LOGIN CREATEROLE CREATEDB REPLICATION BYPASSRLS;

-- Supabase super admin
CREATE USER back_admin NOINHERIT CREATEROLE LOGIN NOREPLICATION PASSWORD 'root';
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION back_admin;
GRANT CREATE ON DATABASE postgres TO back_admin;
ALTER USER back_admin SET search_path = 'auth';
